---
# tasks file for adriagalin.motd
- name: Check motd tail supported
  shell: test -f /etc/update-motd.d/99-footer
  ignore_errors: True
  register: motd_tail_supported
  tags: [ 'motd', 'common' ]

- name: Add motd tail
  template: src=etc/motd.j2 dest=/etc/motd.tail
  when: motd_tail_supported|success
  tags: [ 'motd', 'common' ]

- name: Add motd
  template: src=etc/motd.j2 dest=/etc/motd
  when: motd_tail_supported|failed
  tags: [ 'motd', 'common' ]
